using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VF_RealmPlayersDatabase
{
    public partial class ItemDatabase
    {
        public class ItemInfoDownloader
        {
            System.Net.CookieContainer m_DatabaseWowOneCookieContainer = null;
            DateTime m_DatabaseWowOneCookieContainerCookieCreationTime = DateTime.UtcNow;

            //need the cookie "dbVersion=0" for database.feenixserver.com which is generated by accessing database.feenixserver.com/?version=0
            private System.Net.CookieContainer DatabaseWowOneVanillaCookies_Get()
            {
                if (m_DatabaseWowOneCookieContainer == null
                || (DateTime.UtcNow - m_DatabaseWowOneCookieContainerCookieCreationTime).TotalHours > 1)
                {
                    m_DatabaseWowOneCookieContainer = new System.Net.CookieContainer();
                    var webRequest1 = (System.Net.HttpWebRequest)System.Net.HttpWebRequest.Create("http://database.feenixserver.com/?version=0");
                    webRequest1.CookieContainer = m_DatabaseWowOneCookieContainer;
                    var test = webRequest1.GetResponse();
                    var test2 = test.GetResponseStream();
                    m_DatabaseWowOneCookieContainerCookieCreationTime = DateTime.UtcNow;
                }
                return m_DatabaseWowOneCookieContainer;
            }
            private void DatabaseWowOneVanillaCookies_Clear()
            {
                m_DatabaseWowOneCookieContainerCookieCreationTime = DateTime.UtcNow.AddDays(-1);
            }
            private string DownloadWoWOneDB(int _ItemID, bool _VanillaVersion = false)
            {
                var webRequest = (System.Net.HttpWebRequest)System.Net.HttpWebRequest.Create("http://database.feenixserver.com/ajax.php?item=" + _ItemID);
                webRequest.Timeout = 5000;
                webRequest.ReadWriteTimeout = 5000;
                if (_VanillaVersion == true)
                    webRequest.CookieContainer = DatabaseWowOneVanillaCookies_Get();
                var webResponse = webRequest.GetResponse();
                var responseStream = webResponse.GetResponseStream();
                System.IO.StreamReader reader = new System.IO.StreamReader(responseStream);
                var ajaxItemData = reader.ReadToEnd();
                if (ajaxItemData.StartsWith("$WowheadPower.registerItem"))//Success?
                {
                    string[] itemData = ajaxItemData.Split('{', '}');
                    if (itemData.Length == 3)//Success!(?)
                    {
                        if ((_VanillaVersion == true && webResponse.Headers.Get("Set-Cookie").Contains("dbVersion=0"))
                        || (_VanillaVersion == false && webResponse.Headers.Get("Set-Cookie").Contains("dbVersion=1")))
                        {
                            return ajaxItemData;
                        }
                        else
                            DatabaseWowOneVanillaCookies_Clear();
                    }
                }
                return null;
            }
            public string DownloadWoWOneDB_TBC(int _ItemID)
            {
                return DownloadWoWOneDB(_ItemID, false);
            }
            public string DownloadWoWOneDB_Vanilla(int _ItemID)
            {
                return DownloadWoWOneDB(_ItemID, true);
            }

            public string DownloadWoWHeadXMLData(int _ItemID)
            {
                var webRequest = (System.Net.HttpWebRequest)System.Net.HttpWebRequest.Create("http://www.wowhead.com/item=" + _ItemID + "&xml");
                webRequest.Timeout = 5000;
                webRequest.ReadWriteTimeout = 5000;

                var webResponse = webRequest.GetResponse();
                var responseStream = webResponse.GetResponseStream();
                System.IO.StreamReader reader = new System.IO.StreamReader(responseStream);
                string xmlItemData = reader.ReadToEnd();
                return xmlItemData;
            }
        }
    }
}
