//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VF.RaidDamageWebsite {
    
    
    public partial class AverageOverview {
        
        /// <summary>
        /// RealmControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VF.RaidDamageWebsite.RealmControl RealmControl;
        
        /// <summary>
        /// ClassControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VF.RaidDamageWebsite.ClassControl ClassControl;
    }
}
